### PR TITLE
Added Dark Theme

### PR DESCRIPTION
**Pull request by Lloople**
I've tried to add a dark theme the less intrusive way I could to offer both of them.

I was thinking in a way of `copying` the dist files into the app, like when the config gets published, what do you think? That will solve the problem of having the CSS in the header, and later on the user can add that file to it's minified bundle.

### CODE REVIEW

**Comment by calebporzio** [comment]
Great PR @Lloople, if you can solve the conflicts quick, I'll pull it in!

**Comment by Lloople** [comment]
Done 👍 Neat solution to preserve the `allowIframes` option by the way 🙂

**Comment by calebporzio** [comment]
Hey @Lloople - I think there's an issue with Github's "dark theme". Compare the following outputs from GitDown:

Light Theme:
image

Dark Theme:
image

The Dark Theme seems to prepare most of the syntax for a "dark background" but there are two problems:
1) The background stays the same (I'm guessing it's defined as part of the primer file, not the syntax theme file)
2) The color that get's applied to non-special syntax (like "<" in html tags), is still black (guessing it's the same reason as the background)

Possible solution:

Override the background and text color in GitDown's saas files for dark mode.

What are your thoughts? I pulled this in before testing it sry. (it's not tagged or anything, and it's not a breaking change, so we're good.)

**Comment by Lloople** [comment]
Yeah, something isn’t right there. I’ll take a look this week 👍

**Comment by calebporzio** [comment]
Thanks @Lloople !

**Pull request merged**
